### ISSUE TITLE
Bug Report: "debug_playlistRunBlueprints" breaks 'Reload NRCS Data'

### ISSUE THREAD

**Issue by PeterC89** [nrkno/sofie-core#1139]
### About me

This bug report is posted on behalf of the BBC

### Observed Behavior

Clicking 'Reload NRCS Data' from the Sofie timings bar results in an error message appearing and an error being logged in Core.
Doesn't matter if the rundown is active or inactive in Sofie.
This is with MOS Gateway, unknown if this affects other ingest methods.
```
{"level":"info","message":"UserAction \"resyncRundownPlaylist\" failed: UserError: {\"rawError\":\"errorClass: Error: Rundown \\\"kneAzthqifY_ezDsJvNosujBCcY_\\\" does not have a peripheralDeviceId [500], Error: Rundown \\\"kneAzthqifY_ezDsJvNosujBCcY_\\\" does not have a peripheralDeviceId [500]\\n    at server/api/ingest/lib.ts:120:9\\n    at /opt/core/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\\n => awaited here:\\n    at Function.Promise.await (/opt/core/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\\n    at server/api/ingest/actions.ts:19:15\\n    at /opt/core/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\\n => awaited here:\\n    at Function.Promise.await (/opt/core/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\\n    at server/api/rundown.ts:46:14\\n    at /opt/core/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\\n => awaited here:\\n    at Function.Promise.await (/opt/core/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\\n    at server/api/rundown.ts:42:18\\n    at /opt/core/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\\n => awaited here:\\n    at Function.Promise.await (/opt/core/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\\n    at server/api/client.ts:242:18\\n    at /opt/core/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\",\"message\":{\"key\":\"An internal error occured!\"},\"key\":0,\"errorCode\":500}"}
```

### Expected Behavior

A suitable MOS message should be sent (E.G. `roReq`) to re-request the RO.

### Version

release51

### Severity / Impact

Not a significant issue at this time

**Comment by PeterC89** [comment]
After discussions on Slack it appears that running: `Meteor.call('debug_playlistRunBlueprints', 'kneAzthqifY_ezDsJvNosujBCcY_')` breaks the reload process.
I'll leave this issue open for NRK to decide if this is something that should be fixed or not...

**Comment by nytamin** [comment]
We had a quick chat about this one in the Sofie Team.
Since `debug_playlistRunBlueprints` is an internal debugging function we won't spend time on fixing it, but if anyone else would open a PR with a fix, we'd be happy to accept it.
